# Generated by Django 4.2.7 on 2023-12-20 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("accommodation", "0002_alter_hotel_sequence_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="OperatorMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_code", models.IntegerField()),
                ("external_name", models.CharField(max_length=255)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clients.operator",
                        verbose_name="Master Operator Name",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mapping.provider",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "operators",
                "db_table": "mapping_operator",
                "ordering": ("external_name",),
                "unique_together": {("provider", "external_code")},
            },
        ),
        migrations.CreateModel(
            name="HotelRoomMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_code", models.CharField(max_length=255)),
                ("external_name", models.CharField(max_length=255)),
                (
                    "hotel_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accommodation.hotelroom",
                        verbose_name="Master Room Name",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mapping.provider",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "rooms",
                "db_table": "mapping_hotel_room",
                "ordering": ("hotel_room__hotel__name", "hotel_room"),
                "unique_together": {("hotel_room", "provider", "external_code")},
            },
        ),
        migrations.CreateModel(
            name="HotelMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_code", models.BigIntegerField()),
                ("external_name", models.CharField(max_length=255)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="accommodation.hotel",
                        verbose_name="Master Hotel Name",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mapping.provider",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "hotels",
                "db_table": "mapping_hotel",
                "ordering": ("hotel__name", "external_name"),
                "unique_together": {("provider", "external_code")},
            },
        ),
    ]
