version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    image: datapoint_production_django
    restart: always
    volumes:
      - production_django_media:/app/media
    depends_on:
      - postgres
    env_file:
      - .env
    command: /start
    networks:
      - datapoint

  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: datapoint_production_postgres
    restart: always
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    ports:
      - 5433:5432
    env_file:
      - .env
    networks:
      - datapoint

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    image: datapoint_production_nginx
    restart: always
    depends_on:
      - django
    ports:
      - 80:80
    volumes:
      - production_django_media:/usr/share/nginx/media
    networks:
      - datapoint

networks:
  datapoint:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16