# Generated by Django 4.2.7 on 2024-01-18 07:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE reservations_booking ALTER COLUMN operator_price SET DEFAULT 0;",
        )
    ]
