# Generated by Django 4.2.7 on 2023-12-20 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OperatorGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
            ],
            options={
                "db_table": "clients_operator_group",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("short_name", models.CharField(max_length=12)),
                (
                    "category",
                    models.CharField(
                        choices=[("IC", "IC"), ("PP", "PP")], max_length=2
                    ),
                ),
                (
                    "operator_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clients.operatorgroup",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
