# Generated by Django 4.2.7 on 2024-02-23 14:38

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0002_alter_hotel_sequence_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotel",
            options={
                "ordering": (
                    "area__region__country__name",
                    django.db.models.functions.text.Lower("name"),
                )
            },
        ),
        migrations.AlterField(
            model_name="hotel",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
    ]
