# Generated by Django 4.2.7 on 2024-01-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("ref_id", models.IntegerField(primary_key=True, serialize=False)),
                ("res_id", models.IntegerField()),
                ("hotel_id", models.IntegerField()),
                ("operator_id", models.IntegerField()),
                ("operator_code", models.CharField(max_length=20)),
                ("bkg_ref", models.CharField(max_length=100)),
                ("guest_name", models.CharField(blank=True, max_length=100, null=True)),
                ("sales_date", models.DateField()),
                ("in_date", models.DateField()),
                ("out_date", models.DateField()),
                ("room_type", models.CharField(blank=True, max_length=120, null=True)),
                ("room_code", models.CharField(blank=True, max_length=3, null=True)),
                ("meal", models.CharField(blank=True, max_length=3, null=True)),
                ("adult", models.IntegerField()),
                ("child", models.IntegerField()),
                ("days", models.IntegerField()),
                (
                    "purchase_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=11),
                ),
                (
                    "purchase_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "sales_price",
                    models.DecimalField(decimal_places=4, default=0, max_digits=11),
                ),
                (
                    "sales_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "purchase_price_indicator",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "sales_price_indicator",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("create_date", models.DateField()),
                ("last_modified_date", models.DateField()),
                ("cancellation_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_contract_id",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "purchase_spo_id",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("purchase_spo_name", models.TextField(blank=True, null=True)),
                ("purchase_spo_code", models.TextField(blank=True, null=True)),
                (
                    "sales_contract_id",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("sales_spo_id", models.IntegerField(blank=True, default=0, null=True)),
                ("sales_spo_name", models.TextField(blank=True, null=True)),
                ("sales_spo_code", models.TextField(blank=True, null=True)),
                ("status", models.CharField(max_length=3)),
                ("status4", models.CharField(max_length=3)),
                ("status5", models.CharField(max_length=3)),
            ],
            options={
                "ordering": ("in_date",),
            },
        ),
    ]
