#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

python manage.py collectstatic --noinput
python manage.py migrate

uwsgi --socket :8000 \
      --workers 4 \
      --threads 4 \
      --master \
      --enable-threads \
      --module core.wsgi \
      --buffer-size=32768 \
      --http-timeout=86400
