# Generated by Django 4.2.7 on 2024-03-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ("-created_at",)},
        ),
    ]
