# Generated by Django 4.2.7 on 2024-03-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("gwg", "0001_initial"),
        ("reports", "0002_alter_issue_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="reservation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="gwg.reservation"
            ),
        ),
    ]
